services:
  pinocchio:
    image: 134.209.25.249:5050/frontend/pinocchio:latest
    container_name: pinocchio
    ports:
      - 4200:80
    restart: always
    networks:
      - yurik
networks:
  yurik:
    external: true
