services:
  pinocchio:
    container_name: pinocchio
    build:
      context: .
      dockerfile: Dockerfile
    image: pinocchio:latest
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      - pinocchio
networks:
  pinocchio:
    external: true
