version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: pinocchio
    ports:
      - "4200:80" # Serve on port 4200
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html:ro
    restart: always
